#!/bin/sh
set -eu
#[ "x$EUID" = x0 ] # exit when not root

if [ "$#" = 0 ]
then set -- ${SHELL:-/bin/sh}; break
else while true; do
	case "$1" in
		--) shift; break;;
		[!-]*) break;;
		-h|--help)
			cat - >&2 <<EOF
fake fakeroot, does not "create a fake root environment."
   usage: fakeroot [-l|--lib IGNORED] [-f|--faked IGNORED]
                   [-i IGNORED] [-s IGNORED]
           [-b|--fd-base IGNORED] [-h|--help] [-v|--version]
                   [--] [command]
EOF
			exit;;
		-v|--version)
			[ -t 1 ] && printf %s 'fake fakeroot with commpatible arguments to: ' >&2
			echo 'fakeroot version 1.25.3'
			exit 0
		;;
		-[lfisb]|--lib|--faked|--fd-base) shift;; # IGNORED
		-*) ;;
		*) break;;
	esac
	shift
done; fi

FAKED_MODE=unknown-is-root FAKEROOTKEY=${RANDOM:-12345}${RANDOM:-67890} "$@"
